---
:dataminer_definition: production_run_allocated_setups
:actions:
- :url: "/production/product_setups/product_setups/$:product_setup_id$"
  :text: view product setup
  :icon: view-show
  :title: View
  :hide_if_null: product_setup_id
- :url: "/production/runs/product_resource_allocations/$:id$/preview_label"
  :text: Preview label
  :icon: photo
  :title: Peview label
  :popup: true
:conditions:
  :standard:
  - :col: r.id
    :op: "="
    :val: "$:production_run_id$"
  :for_copy:
  - :col: r.id
    :op: "="
    :val: "$:production_run_id$"
:multiselect:
  :copy:
    :url: "/production/runs/product_resource_allocations/$:id$/copy"
    :section_caption: Choose resources to get a copy of this allocation
    :multiselect_save_method: remote
    :conditions: :for_copy
:hide_for_client:
  hb:
  - system_code
  - fg_marks
  - gtin_code
  - packing_specification_item_code
  um:
  - system_code
  - fg_marks
  - gtin_code
  - packing_specification_item_code
  ud:
  - system_code
  - fg_marks
  - gtin_code
  - packing_specification_item_code
  sr:
  - system_code
  - fg_marks
  - gtin_code
  - packing_specification_item_code
  srp:
  - system_code
  - fg_marks
  - gtin_code
  - packing_specification_item_code
  hl:
  - packing_specification_item_code
  kr:
  - id
  - product_setup_code
  - system_code
  - fg_marks
