---
:dataminer_definition: production_runs
:actions:
- :url: "/production/runs/production_runs/$:id$"
  :text: view
  :icon: view-show
  :title: View
  :popup: true
- :url: "/production/runs/production_runs/$:id$/edit"
  :text: edit
  :icon: edit
  :title: Edit
  :popup: true
  :hide_if_true: setup_complete
- :url: "/production/runs/production_runs/$:id$/clone"
  :text: clone this run
  :icon: copy
  :title: Clone this run
  :popup: true
  :hide_if_false: setup_complete
- :separator: true
- :url: "/production/runs/production_runs/$:id$/close"
  :text: close this run
  :icon: lock-closed
  :title: Close this run
  :popup: true
  :hide_if_false: completed
  :hide_if_true: closed
- :url: "/production/runs/production_runs/$:id$/complete_setup"
  :text: mark setup as complete
  :icon: toggle-on
  :title: Mark setup as complete
  :popup: true
  :hide_if_true: setup_complete,reconfiguring
- :url: "/production/runs/production_runs/$:id$/un_complete_setup"
  :text: un-complete setup
  :icon: toggle-off
  :title: Un-complete setup
  :popup: true
  :hide_if_false: setup_complete
  :hide_if_true: running,reconfiguring,completed
- :url: "/production/runs/production_runs/$:id$/execute_run"
  :text: execute run
  :icon: play
  :title: Execute run
  :popup: true
  :hide_if_true: running,completed
  :hide_if_false: setup_complete
- :url: "/production/runs/production_runs/$:id$/re_execute_run"
  :text: re-execute run
  :icon: play
  :title: Re-execute run
  :popup: true
  :hide_if_false: reconfiguring
- :url: "/production/runs/production_runs/$:id$/complete_run"
  :text: complete all run stages
  :icon: minus-solid
  :title: Complete all run stages
  :popup: true
  :hide_if_true: reconfiguring
  :hide_if_false: running,tipping,labeling
- :url: "/production/runs/production_runs/$:id$/complete_stage"
  :text: complete current run stage
  :icon: minus-outline
  :title: Complete current run stage
  :popup: true
  :hide_if_true: reconfiguring
  :hide_if_false: running
- :url: "/production/runs/production_runs/$:id$/re_configure"
  :text: re-configure
  :icon: edit
  :title: Re-configure
  :popup: true
  :prompt: Are you sure you want to re-configure this run?
  :hide_if_false: running
  :hide_if_true: reconfiguring
- :separator: true
- :url: "/production/runs/production_runs/$:id$/select_template"
  :text: select template
  :icon: arrow-left
#  :title: Select Product Setup Template
  :popup: true
  :hide_if_true: setup_complete,reconfiguring
- :url: "/production/runs/production_runs/$:id$/allocate_setups"
  :text: allocate product setups
  :icon: list
  :hide_if_null: product_setup_template_id
  :hide_if_false: allocation_required
  :hide_if_true: view_allocs
- :url: "/production/runs/production_runs/$:id$/allocate_setups"
  :text: view allocated product setups
  :icon: list
  :hide_if_false: view_allocs,allocation_required
- :url: "/production/runs/production_runs/$:id$/view_setups"
  :text: view setups
  :icon: list
  :title: Select Product Setup Template
  :hide_if_null: product_setup_template_id
- :url: "/production/runs/production_runs/$:id$/allocate_target_customer"
  :text: allocate target customers
  :icon: arrow-left
  :hide_if_null: product_setup_template_id
  :hide_if_false: allocation_required
  :hide_if_true: view_allocs
- :url: "/production/runs/production_runs/$:id$/allocate_target_customer"
  :text: view allocated target customer
  :icon: list
  :hide_if_false: view_allocs
- :url: "/production/runs/production_runs/$:id$"
  :text: delete
  :icon: delete
  :is_delete: true
  :popup: true
  :hide_if_true: setup_complete,reconfiguring
- :submenu:
    :text: list
    :items:
      - :url: "/list/rmt_deliveries/with_params?key=production_run_deliveries&ids=$:delivery_ids$"
        :text: deliveries
        :icon: list
        :hide_if_false: has_deliveries
      - :url: "/list/rmt_bins/with_params?key=production_run_bin&id=$:id$"
        :text: bins
        :icon: list
        :hide_if_false: has_bins
      - :url: "/list/rmt_bins/with_params?key=production_run_rebin&id=$:id$"
        :text: rebins
        :icon: list
        :hide_if_false: has_rebins
      - :url: "/list/pallets_view/with_params?key=production_run_pallets&production_run_id=$:id$"
        :text: pallets
        :icon: list
        :hide_if_false: has_pallets
      - :url: "/list/pallet_sequences_view/with_params?key=production_run_sequences&id=$:id$"
        :text: pallet sequences
        :icon: list
        :hide_if_false: has_pallets
      - :url: "/list/cartons/with_params?key=production_run_cartons&id=$:id$"
        :text: cartons
        :icon: list
        :hide_if_false: has_cartons
      - :url: "/list/palletizer_pallets/with_params?key=production_run_pallets&production_run_id=$:id$"
        :text: palletizer pallets
        :icon: list
        :hide_if_false: has_pallets
- :separator: true
- :url: "/production/runs/production_runs/$:id$/show_stats"
  :text: view run stats
  :icon: view-show
  :title: View run stats
  :popup: true
- :url: "/production/runs/production_runs/$:id$/run_reports"
  :text: reports
  :icon: printer
  :title: Reports for Production Run $:id$
  :popup: true
- :url: "/quality/qc/qc_samples/production_run_sample/$:id$/production_run"
  :text: QC
  :icon: check-square
  :title: QC for Production Run $:id$
  :popup: true
- :separator: true
- :url: "/development/statuses/list/production_runs/$:id$"
  :text: status
  :icon: information-solid
  :title: Status
  :popup: true
- :url: "/development/transactions/list/production_runs/$:id$"
  :text: transactions
  :icon: code
  :title: Transactions
  :popup: true
- :separator: true
- :submenu:
    :text: rebins
    :items:
      - :url: /production/runs/production_runs/$:id$/rebins
        :text: create rebin
        :icon: add-solid
        :popup: true
      - :url: "/list/run_rebins/multi?key=standard&id=$:id$"
        :text: print barcodes
        :popup: true
      - :url: "/production/runs/production_runs/$:id$/print_rebin_labels"
        :text: print labels
        :popup: true
- :separator: true
- :url: "/production/runs/production_runs/$:id$/refresh_pallet_data"
  :text: refresh pallet data
  :icon: play
  :popup: false
- :separator: true
- :url: "/production/runs/production_runs/$:id$/view_bin_tipping_criteria"
  :text: view bin tipping criteria
  :icon: view-show
  :popup: true
  :show_if_env_var: CLIENT_CODE:kr
:conditions:
  :standard:
    - :col: production_runs.id
      :op: IN
      :val: $:ids$
:page_controls:
- :control_type: :link
  :url: "/production/runs/production_runs/new"
  :text: New Production Run
  :style: :button
  :behaviour: :popup
