= App config
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== App configuration

The application environment is set in the `RACK_ENV` environment variable.

Environments can be:

* development (default)
* production
* test

Environment variable loading uses the dotenv gem (https://github.com/bkeepers/dotenv).

Development environment variables are set in the `.env` file in the root dir.

Per-machine overrides can be specified in a `.env.local` file (which is not checked in to version control).

Client settings can be checked in-app from the link:/client_settings[] link.

=== Client settings

Client settings are defined in the `.env.local` file on the client's server.

Rules for environment variables are defined in `config/client_settings_loader.rb`. Whenever a new client setting is required, this file must be updated with the variable and its rules and description.

Environment variables are classified in one of the folowing ways:

FIXED_RULES :: These are set in the `.env` file and are fixed - never to be changed. e.g. `APP_CAPTION`.
RULES :: These are set in `.env.local`. and are a mix of optional and required settings that are not rules. e.g. `SYSTEM_MAIL_SENDER`. These are the main per-client settings.
DEVELOPER_RULES :: These are set in `.env.local` and are typically set to alter logging behaviour. e.g. `VERBOSE_ROBOT_FEEDBACK_LOGGING`.
Other :: There are other optional settings (typically for developers only) that do not have to be present and are not loaded into `AppConst`. e.g. `LOGSQLTOFILE`.


Use `bundle exec rake developers:setup` to get `.env.local` to add any required environment variables. All required veriables are appended to the file each time, so careful culling of the file is required after the task is run.

=== AppConst

This file (`config/app_const.rb`) stores "global" constants for use throuhgout the application.

Reference a constant in code like this:
[source,ruby]
----
AppConst::CLIENT_CODE
----

AppConst has several fixed constants like this:
[source,ruby]
----
BUILDUP_PALLET_MIX = 'BUILDUP'
PALLETIZING_PALLET_MIX = 'PALLETIZING'
----

but there are also constants that are loaded from environment variables -- the _client settings_.

Client settings are loaded from `ClientSettingsLoader` according to the rules in that file -- e.g.

.config/client_settings_loader.rb
[source,ruby]
----
# Use :env_key as the ENVIRONMENT VARIABLE name in .env.local:
# e.g.
# CLIENT_CODE=acme
# GLN_OR_LINE_NUMBERS=123,456,999

RULES = {
  CLIENT_CODE: { env_key: 'CLIENT_CODE',                                      <1>
                 required: true,                                              <2>
                 desc: 'Short, lowercase code to identify...(trimmed)' },     <3>
  GLN_OR_LINE_NUMBERS: { env_key: 'GLN_OR_LINE_NUMBERS',
                         required: true,
                         array_split: ',',                                    <4>
                         desc: 'A comma-separated list of GLN ...(trimmed)' },
  EST_PALLETS_PACKED_PER_YEAR: { env_key: 'EST_PALLETS_PACKED_PER_YEAR',
                                 default: 25_000,                             <5>
                                 format: :integer,                            <6>
                                 desc: 'An estimate of ...(trimmed)' },
}
----
<1> The hash's key (`CLIENT_CODE`) will be used for `AppConst::CLIENT_CODE` and the value of `:env_key` (here also `CLIENT_CODE`) is the environment variable name used to load the value.
<2> If `required` is `true`, an exception will be raised if there is no matching environment variable at startup.
<3> A description is always required for documentation purposes.
<4> The `:array_split` value is the string for the loader to use to split the env var's value into an array.
<5> A `:default` value is applied if there is no matching environment variable.
<6> Specify `:integer` as the `:format` value to store the const as an integer.

== Client Rules

Client rules are a special case of AppConst.

A set of client rules are defined in a class in `lib/client_rules`. This class is instantiated in AppConst as a constant whose name begins with `CR_`.
Methods are called on the constant to check behaviour rules for the current client (as defined in the environment variable `CLIENT_CODE`).

These classes must follow the following rules:

1. Part of `Crossbeams` module.
2. Name is made up of three parts - `Client`, descriptive and `Rules` (e.g. `ClientRunRules`)
3. Inherit from `BaseClassRules`.
4. `include Crossbeams::AutoDocumentation`.
5. Implement a constant named `CLIENT_SETTINGS` - hash where keys are the `CLIENT_CODE` as a symbol and the values are hashes of settings and their values.
6. Initialize method must set `@settings` to the `CLIENT_SETTINGS` value for the passed-in `client_code` converted to a symbol.
7. Each method must implement the arg: `explain: false`.
8. Each method must return a string explaning the method if it is called with `explain: true`.
9. The method body should return something relevant to the calling code otherwise.
10. Client settings that just return their value do not have to be defined in methods. They are still called as methods though.

=== Testing code that relies on client rules.

AppConst implements a constant named `TEST_SETTINGS` with an attribute named `client_code` defaulted to the current `CLIENT_CODE`.
When a test is run, this client code can be changed to test different behaviour for another client.

NOTE: You can set the client code back to the boot client code at the end of your test with an `ensure` block.

e.g. This code expects different values for `allocation_required` for two different clients:
[source,ruby]
----
def test_create_production_run
  attrs = fake_production_run.to_h.reject { |k, _| k == :id }
  AppConst::TEST_SETTINGS.client_code = 'hl'
  id = repo.create_production_run(attrs)
  alloc = repo.get(:production_runs, id, :allocation_required)
  assert alloc

  AppConst::TEST_SETTINGS.client_code = 'hb'
  id = repo.create_production_run(attrs)
  alloc = repo.get(:production_runs, id, :allocation_required)
  refute alloc
ensure
  AppConst::TEST_SETTINGS.client_code = AppConst::TEST_SETTINGS.boot_client_code
end
----

=== Example client rules

[source,ruby]
----
module Crossbeams
  class ClientRunRules < BaseClientRules
    include Crossbeams::AutoDocumentation

    CLIENT_SETTINGS = {
      hb: { run_allocations: false,
            packing_container: 'CARTON' },
      hl: { run_allocations: true,
            packing_container: 'BIN' }
    }.freeze

    def initialize(client_code)
      @settings = CLIENT_SETTINGS.fetch(client_code.to_sym)
    end

    def no_run_allocations?(explain: false)
      return 'Does this client not do allocation of product setup to resource?' if explain

      !setting(:run_allocations)
    end
  end
end

> CR_RUN = Crossbeams::ClientRunRules.new('hb')
# => #<Crossbeams::ClientRunRules:0x000055a76a51d9e0 @settings={:run_allocations=>false, :packing_container=>"CARTON"}>
> CR_RUN.no_run_allocations?(explain: true)
# => "Does this client not do allocation of product setup to resource?"
> CR_RUN.no_run_allocations?
# => true
> CR_RUN.packing_container(explain: true)
# => "Packing container"
> CR_RUN.packing_container
# => "CARTON"

----
