= Export data
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== Export data

Data exports are carried out by calling:
[source,sh]
----
RACK_ENV=production bundle exec rake app:export[keyname]
----
Where `keyname` is a key in `config/export_data_config.yml` (which encapsulates the rules for how to execute the `keyname` export task).

=== Configuration

A sample configuration file could look like this:
[source,yml]
----
pallet_sequences:
  grid: all_pallet_sequences                       #<1>
  out_dir: /home/nspack/export_data                #<2>
  export_hidden_fields: true                       #<3>
  boolean_as_yn: false                             #<4>
  prefix_long_numbers_with_quote: false            #<5>
  zip_for_mail: true                               #<6>
  email:                                           #<7>
    to: james@nosoft.biz
    subject: All pallets report
    body: All pallets report generated from NSpack
  conditions:                                      #<8>
    - col: season
      op: =
      val: 2020
shipped_pallets:
  report: shipped_pallets                          #<9>
  out_dir: /home/nspack/export_data
----
<1> Use `all_pallet_sequences.yml` **grid** definition. _Required_. See point (9).
<2> Output directory. _Required_.
<3> _Optional_. Default is `false` (hidden columns are ignored). Set to `true` to include hidden columns.
<4> _Optional_. Default is `true`. If `true`, boolean columns export as `"Y"` for `true` and `"N"` for `false`.
<5> _Optional_. Default is `true`. If `true`, columns containing only numbers longer than 12 will be exported with a leading `'`. (e.g. pallet_number - so spreadsheets treat them as text).
<6> _Optional_. Default is `false`. If `true`, a zip file will be created.
<7> _Optional_. If present, these settings will be used to email a copy of the output file.
<8> _Optional_. If present, these conditions will be converted into a where clause for the extract.
<9> Use `shipped_pallets.yml` **report** definition. _Required_. See point (1).
