= How to produce a Jasper report
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== How to produce a Jasper report

=== Installation config

At installation there are two environment variables that need to be set up: `JRUBY_JASPER_HOST_PORT` and `JASPER_REPORTS_PATH`.

* `JRUBY_JASPER_HOST_PORT` is the port at which the `jruby_japser` interface is running. The default value is `9998`.
* `JASPER_REPORTS_PATH` is a fully qualified path that points to the directory containing the designed jasper report files.

`jruby_jasper` must be running on the system, listening on the same port as `JRUBY_JASPER_HOST_PORT`.
See https://github.com/NoSoft-SA/jruby_jasper (README and INSTALL docs).

=== Per industry/client overrides for Japser reports

Reports are stored in 3 ways - per system, per industry or per client.

* The per-system reports are used by all installations.
* The per-industry reports will differ per industry (melons vs citrus for example).
* The per-client reports are tailored specifically to the client.

For a per-industry report, the `parent_folder` parameter must be set to the value of `AppConst::RPT_INDUSTRY`.

For a per-client report, the system will ignore the `parent_folder` parameter and use the client-specific version of the report (if it exists). i.e. this report will be used instead of a per-system or per-industry report without any need to specify this in the calling code.

=== UI link to load report in a new window

To load the report in a new window, the link must include `data-loading-window="true"`.

e.g.
[source, ruby]
----
page.section do |section|
  section.add_control(control_type: :link,
                      text: 'Load Jasper report',
                      url: '/render_jasper',
                      loading_window: true,
                      style: :button)
end
----

=== Generating a report

Use the `JasperParams` class and the `CreateJasperReport` service to print or create a pdf/csv/xlsx/rtf report.
The service returns a success/failure response object. A successful response has the name of the generated file as the instance value (for any mode other than `:print` - which will be nil).

NOTE: In a route, to display a generated pdf in a loading window, return a JSON hash with the key `location` and the value set to the file name.

First create a `JasperParams` object with the report name, user and report parameters:
[source, ruby]
----
jasper_params = JasperParams.new('report_name',
                                 current_user.login_name,
                                 param1: 'val',
                                 param2: 123)
----
Then - if any defaults need to be changed, set them:
[source, ruby]
----
jasper_params.mode = :xls
jasper_params.file_name = 'report_name_tweaked'
----
Available `jasper_params` attributes are:

|===
|attribute |description |default

|mode
|Can be `:pdf`, `:xls`, `:csv`, `:rtf` or `:print`
|`:pdf`

|file_name
|The file name (without path/ext) for the output
|Same as `report_name`

|parent_folder
|Provided if the report dir is not an immediate subdir of `JASPER_REPORTS_PATH`. Typically set to `AppConst::RPT_INDUSTRY`
|`nil`

|printer
|The printer name. Only used when `mode` is `:print`
|`nil`

|return_full_path
|If false, path is relative to `public` dir. If true, the full path is returned.
|`false`

|===

Call the service to generate or print the report:
[source, ruby]
----
res = CreateJasperReport.call(jasper_params)
----
Display the report:
[source, ruby]
----
# Route
res = interactor.create_report

if res.success
  # For :print mode:
  show_json_notice('Sent to printer')

  # For any other mode:
  change_window_location_via_json(UtilityFunctions.cache_bust_url(res.instance), request.path)

  # When generating XLSX or RTF files which are downloaded by the browser,
  # add download: true so the browser window stops showing the spinner.
  change_window_location_via_json(UtilityFunctions.cache_bust_url(res.instance),
                                  request.path,
                                  download: true)
else
  show_error(res.message, fetch?(r))
end
----

=== Debugging/Logging

The `jruby_jasper` app uses Java's Log4j2 logging. The default is to log to console at error level. When running as a systemd service, this output appears in syslog (typically `/var/log/syslog`). The settings can be tweaked by editing `config/log4j2.xml` in the `jruby_jasper` dir.

Any change to the config file requires a restart of the service (e.g. `sudo systemctl restart jruby_jasper.service`)

=== Generate and email a report

There is a job `DevelopmentApp::EmailJasperReport` which will create the report(s) and email the results as an attachment.

Parameter options for the `run` method are:

* `:user_name` - the user name (typically `current_user.login_name`)
* `:email_settings` - the to/subject and body values for the email.
* `:reports` - an array of parameters for one or more reports.

An example from a route:
[source,ruby]
----
r.on 'email_report', Integer do |id|
  r.get do
    interactor = TheInteractor.new(current_user, {}, { route_url: request.path }, {})
    email_opts = interactor.email_report_defaults(id, current_user)
    show_partial_or_page(r) do
      Development::Generators::General::Email.call(remote: true,
                                                   email_options: email_opts,
                                                   action: "/email_report/#{id}")
    end
  end
  r.post do
    opts = {
      email_settings: params[:mail],
      user: current_user.login_name,
      reports: [
        {
          report_name: 'the_report',
          file: 'your_report_sir',
          report_params: { the_report_id: id }
        }
      ]
    }
    DevelopmentApp::EmailJasperReport.enqueue(opts)
    show_json_notice('Report queued to be generated and sent')
  end
end
----

To generate more than one report attachment, alter the opts in the POST route above:
[source,ruby]
----
opts = {
  email_settings: params[:mail],
  user: current_user.login_name,
  reports: [
    {
      report_name: 'the_report',
      file: 'your_report_sir',
      report_params: { the_report_id: id }
    },
    {
      report_name: 'the_other_report',
      file: 'your_second_report_sir',
      report_params: { the_report_id: id, sky: 'blue' }
    }
  ]
}
----
