= How to produce a Jasper report
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== How to produce a Jasper report

=== Installation config

At installation there are two environment variables that need to be set up: `JASPER_REPORTING_ENGINE_PATH` and `JASPER_REPORTS_PATH`.

* `JASPER_REPORTING_ENGINE_PATH` is a fully qualified path that points to the directory where the `JasperReportPrinter.jar` is installed.
* `JASPER_REPORTS_PATH` is a fully qualified path that points to the directory containing the designed jasper report files.

=== Per industry/client overrides for Japser reports

Reports are stored in 3 ways - per system, per industry or per client.

* The per-system reports are used by all installations.
* The per-industry reports will differ per industry (melons vs citrus for example).
* The per-client reports are tailored specifically to the client.

For a per-industry report, the `parent_folder` parameter must be set to the value of `AppConst::RPT_INDUSTRY`.

For a per-client report, the system will ignore the `parent_folder` parameter and use the client-specific version of the report (if it exists). i.e. this report will be used instead of a per-system or per-industry report without any need to specify this in the calling code.

=== UI link to load report in a new window

To load the report in a new window, the link must include `data-loading-window="true"`.

e.g.
[source, ruby]
----
page.section do |section|
  section.add_control(control_type: :link,
                      text: 'Load Jasper report',
                      url: '/render_jasper',
                      loading_window: true,
                      style: :button)
end
----

=== Generating a report

Use the `CreateJasperReport` service to create a pdf report.
The service returns a success/failure response object. A successful response has the name of the generated file as the instance value for `GENERATE` mode, or nil for `PRINT` mode..

NOTE: To show a pdf in a loading window, return a JSON hash with the key `location` and the value set to the generated file.
[source, ruby]
----
# Interactor:
def create_report
  CreateJasperReport.call(report_name: 'abc',
                          user: current_user.login_name,
                          file: output_file_name_to_be_saved_without_extension_or_path,
                          debug_mode: <optional, true/false>
                          parent_folder: <optional, typically set to AppConst::RPT_INDUSTRY>
                          params: hash_of_report_parameters)
end

# Route
res = interactor.create_report

if res.success
  # For PRINT MODE:
  show_json_notice('Sent to printer')

  # For GENERATE MODE:
  change_window_location_via_json(UtilityFunctions.cache_bust_url(res.instance), request.path)

  # When generating XLS or RTF files which are downloaded by the browser,
  # add download: true so the browser window stops showing the spinner.
  change_window_location_via_json(UtilityFunctions.cache_bust_url(res.instance),
                                  request.path,
                                  download: true)
else
  show_error(res.message, fetch?(r))
end
----

If params includes `keep_file: true`, the script that runs the report will be saved in the tmp dir below the root.

NOTE: If `debug_mode` is present and true, logging of variable values etc. will take place. Check the console or something like `/var/log/nginx/error.log` for output.

The report is generated with the following default parameters which can be overridden by including them in the `params` hash (Note the **case** of the keys is important)):

- MODE: `GENERATE`. Generate will create a file, PRINT will send the report directly to the printer.
- printer: `no_printer`. In PRINT mode, this MUST be provided.
- OUT_FILE_TYPE: `PDF`. This can be PDF, CSV, XLS, RTF. Ignored in PRINT mode.
- top_level_dir: `''`. Use this if the report is stored in a subdir of the report dir.

[NOTE]
====
If a report parameter sent to Jasper has to be a boolean value, it must be expressed like this:
[source, ruby]
----
param_name: 'false|boolean' # Jasper gets param_name: false

# The following will not work correctly:
param_name: false           # Jasper gets param_name: 'false'
----
====

[NOTE]
====
If a report parameter sent to Jasper has to be a date value, it must be expressed like this:
[source, ruby]
----
# if Ruby Date:
param_name: "#{attrs[:from_date]} 00:00:00|date"

# if Ruby DateTime/Time:
param_name: "#{attrs[:from_date_time].strftime('%Y-%m-%d %H:%M:%S')}|date"
----
====

[NOTE]
====
If a report parameter sent to Jasper has to be an array of integers, it must be presented as a string of comma-separated numbers (no spaces!) and expressed like this:
[source, ruby]
----
list_of_ids ='1,2,3'
param_name: "#{list_of_ids}|intarray"  # => [1,2,3]
----
====

[NOTE]
====
Other methods of forcing parameter datatypes are:

* `|integer` - ensure the value is an integer. This should happen automatically when the string can be coerced to int.
* `|string` - ensure the value is a string. This is required if the value could be an integer but should be sent to Jasper as a string.
====

=== Generate and email a report

There is a job `DevelopmentApp::EmailJasperReport` which will create the report(s) and email the results as an attachment.

Parameter options for the `run` method are:

* `:user_name` - the user name (typically `current_user.login_name`)
* `:email_settings` - the to/subject and body values for the email.
* `:reports` - an array of parameters for one or more reports.

An example from a route:
[source,ruby]
----
r.on 'email_report', Integer do |id|
  r.get do
    interactor = TheInteractor.new(current_user, {}, { route_url: request.path }, {})
    email_opts = interactor.email_report_defaults(id, current_user)
    show_partial_or_page(r) do
      Development::Generators::General::Email.call(remote: true,
                                                   email_options: email_opts,
                                                   action: "/email_report/#{id}")
    end
  end
  r.post do
    opts = {
      email_settings: params[:mail],
      user: current_user.login_name,
      reports: [
        {
          report_name: 'the_report',
          file: 'your_report_sir',
          report_params: { the_report_id: id }
        }
      ]
    }
    DevelopmentApp::EmailJasperReport.enqueue(opts)
    show_json_notice('Report queued to be generated and sent')
  end
end
----

To generate more than one report attachment, alter the opts in the POST route above:
[source,ruby]
----
opts = {
  email_settings: params[:mail],
  user: current_user.login_name,
  reports: [
    {
      report_name: 'the_report',
      file: 'your_report_sir',
      report_params: { the_report_id: id }
    },
    {
      report_name: 'the_other_report',
      file: 'your_second_report_sir',
      debug_mode: true, # If you want to see what variables were set
      report_params: { the_report_id: id, sky: 'blue' }
    }
  ]
}
----
