= Response objects
:toc:

link:/developer_documentation/start.adoc[Back to documentation home]

== Response objects

Response objects are defined in the module `Crossbeams::Responses`.

They are used to return a structured response from a method that has the following payload:

success :: A boolean which is true if the method succeeded.
instance :: Optional. Relevant data.
errors :: Optional. Specific error messages - typically for validation of fields.
message :: A message to describe the result.

=== Setup

A class should `include Crossbeams::Responses`. Note that classes inheriting from `BaseRepo`, `BaseInteractor` and `BaseService` already include the module.

Methods in the class can generate crossbeams responses using the methods:

* `success_response`
* `ok_response`
* `failed_response`
* `validation_failed_message_response`
* `validation_failed_response`
* `mixed_validation_failed_response`
* `valid_response`

NOTE: There is also a helper method `unwrap_failed_response` which takes a response and returns the message string (including validation errors if present).

See link:/yarddocthis/lib=crossbeams_responses.rb[Crossbeams::Responses methods] for a list of the method definitions described below.

=== Success responses

These are `success_response` and `ok_response`. They always return `success == true` and a `message`.
Use `ok_response` when you just need to denote success and the `message` is unimportant.

success_response :: Requires a message.
ok_response :: Returns message 'ok'.

=== Failure response

This method is called `failed_response` and always returns `success == false` and a `message`.
Can optionally return `instance`.

failed_response :: Requires a failure message.

=== Validation responses

There are three validation responses. They always returns `success == false` and `message == 'Validation error'`.
The `errors` should always return validation error message(s) per field in error.

validation_failed_message_response :: Use this to just pass the validation errors.
validation_failed_response :: Use this to pass the validation errors with an instance.
mixed_validation_failed_response :: Use this to combine two or more validation results.

Validation responses are usually called with a `Dry::Validation::Result` instance, but can also be called with a `Hash` or `OpenStruct`.

`validation_failed_message_response` can be called with messages in either a hash or a string. A Hash behaves as if `validation_failed_response` was called with the standard `Dry::Validation` object; while a string will display just a base validation error.
[source,ruby]
----
# e.g. with errors for `name` and `email` columns:
validation_failed_message_response(name: ['required', 'too short'], email: ['required'])

# These two will both render the same base error message:
validation_failed_message_response(base: ['A general validation for the whole form'])
validation_failed_message_response('A general validation for the whole form')
----


Use `valid_response` when you just need to denote that a validation process succeeded without running a dry validation.
The return value from this method will always return `true` for `success?` and `false` for `failure?`.
If the code calls for it, you can supply a Hash value which will be returned when calling `to_h` on the result. This defaults to an empty hash.

=== Helpers

Helper methods are provided to make common situations simpler to code.

unwrap_failed_response :: Use this to return the error message (and its validation errors when present) from a response object which has `success == false`.
