require:
  - ./lib/rubocop/cops/lint_env

AllCops:
  Exclude:
    - db/**/*
    - test/**/*
    - tmp/**/*

# New (pending) cops:
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true


# END of pending cops

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# TODO: Remove the Max option when upgrading beyond 0.89
Metrics/AbcSize:
  Max: 17
  Exclude:
    - '**/factories/*.rb'
    - '**/lib/**/views/**/*.rb'
    - '**/test_*.rb'

# TODO: Remove the Max option when upgrading beyond 0.89
Metrics/PerceivedComplexity:
  Max: 7

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Lint/Env:
  Enabled: false
  Include:
    - '**/*.rb'
  Exclude:
    - '**/config/app_const.rb'
    - '**/config/client_settings_loader.rb'
    - '**/config/environment.rb'
    - '**/config/puma.rb'
    - 'app_loader.rb'
    - 'scripts/base_script.rb'
  AllowedEnv:
    - HOME
    - GRID_QUERIES_LOCATION
    - JASPER_REPORTING_ENGINE_PATH
    - JASPER_REPORTS_PATH
    - LOGFULLMESSERVERCALLS
    - NO_ERR_HANDLE
    - NO_RUN_ALLOCATION
    - RACK_ENV
    - ROOT
    - RUN_FOR_RMD
    - VERSION
