edi_out_ps:
  db_sequence_name: doc_seqs_edi_out_ps
  data_type: :integer
  table: edi_out_transaction
  column: edi_sequence_number
edi_out_po:
  db_sequence_name: doc_seqs_edi_out_po
  data_type: :integer
  table: edi_out_transaction
  column: edi_sequence_number
edi_out_palbin:
  db_sequence_name: doc_seqs_edi_out_palbin
  data_type: :integer
  table: edi_out_transaction
  column: edi_sequence_number
edi_out_hcs:
  db_sequence_name: doc_seqs_edi_out_hcs
  data_type: :integer
  table: edi_out_transaction
  column: edi_sequence_number
edi_out_uistk:
  db_sequence_name: doc_seqs_edi_out_uistk
  data_type: :integer
  table: edi_out_transaction
  column: edi_sequence_number
dummy_number:
  db_sequence_name: doc_seqs_dummy_number
  data_type: :integer
  table: some_tables
  column: dummy_number
dummy_invoice:
  db_sequence_name: doc_seqs_inv
  data_type: :string
  prefix: INV
  digit_length: 7
  table: invoices
  column: invoice_ref
