---
:caption: Allocated setups for production run
:sql: "SELECT\r\n  a.id,\r\n  parent.plant_resource_code AS pack_station,\r\n  sysres.system_resource_code
  AS module,\r\n  p.plant_resource_code,\r\n  a.product_setup_id,\r\n  fn_product_setup_code
  (s.id) AS product_setup_code,\r\n  fn_packing_specification_code (psi.id) AS packing_specification_item_code,\r\n
  \ fn_work_order_item_code (woi.id) AS work_order_item_code,\r\n  pm_boms.system_code,\r\n
  \ CONCAT(marks.mark_code, '_', COALESCE(array_to_string(pm_marks.packaging_marks,
  '_'), ' ')) AS fg_marks,\r\n  s.gtin_code,\r\n  a.label_template_id,\r\n  l.label_template_name,\r\n
  \ a.packing_method_id,\r\n  pm.packing_method_code,\r\n  a. active,\r\n  a.production_run_id,\r\n
  \ s.rebin,\r\n  CASE \r\n  WHEN s.rebin THEN  'warning'\r\n  WHEN parent_type.plant_resource_type_code
  = 'BIN_FILLER_ROBOT' THEN\r\n  'warning'\r\n  ELSE\r\n    NULL\r\n  END AS colour_rule\r\nFROM\r\n
  \ production_runs r\r\n  JOIN tree_plant_resources t ON t.ancestor_plant_resource_id
  = r.production_line_id\r\n  JOIN plant_resources p ON p.id = t.descendant_plant_resource_id\r\n
  \   AND (\"p\".\"plant_resource_type_id\" = (\r\n        SELECT\r\n          \"id\"\r\n
  \       FROM\r\n          \"plant_resource_types\"\r\n      WHERE\r\n        \"plant_resource_type_code\"
  = 'ROBOT_BUTTON')\r\n      OR \"p\".\"plant_resource_type_id\" = (\r\n        SELECT\r\n
  \         \"id\"\r\n        FROM\r\n          \"plant_resource_types\"\r\n        WHERE\r\n
  \         \"plant_resource_type_code\" = 'PACK_POINT'))\r\n    LEFT OUTER JOIN product_resource_allocations
  a ON a.production_run_id = r.id\r\n    AND a.plant_resource_id = p.id\r\n  LEFT
  OUTER JOIN product_setups s ON s.id = a.product_setup_id\r\n  LEFT OUTER JOIN packing_specification_items
  psi ON psi.id = a.packing_specification_item_id\r\n  LEFT OUTER JOIN work_order_items
  woi ON woi.id = a.work_order_item_id\r\n  LEFT OUTER JOIN label_templates l ON l.id
  = a.label_template_id\r\n  LEFT OUTER JOIN tree_plant_resources tpl ON tpl.descendant_plant_resource_id
  = p.id\r\n    AND tpl.path_length = 1\r\n  LEFT OUTER JOIN plant_resources parent
  ON parent.id = tpl.ancestor_plant_resource_id\r\n  LEFT OUTER JOIN plant_resource_types
  parent_type ON parent_type.id = parent.plant_resource_type_id\r\n  LEFT OUTER JOIN
  system_resources sysres ON sysres.id = parent.system_resource_id\r\n  LEFT OUTER
  JOIN packing_methods pm ON pm.id = a.packing_method_id\r\n  LEFT OUTER JOIN pm_boms
  ON pm_boms.id = s.pm_bom_id\r\n  LEFT OUTER JOIN marks ON marks.id = s.mark_id\r\n
  \ LEFT OUTER JOIN pm_marks ON pm_marks.id = s.pm_mark_id\r\n  ORDER BY parent.plant_resource_code,
  p.plant_resource_code"
:limit: 
:offset: 
:external_settings:
  :colour_key:
    warning: Bin-filler
:columns:
  id:
    :name: id
    :sequence_no: 1
    :caption: Id
    :namespaced_name: a.id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  pack_station:
    :name: pack_station
    :sequence_no: 2
    :caption: Pack station
    :namespaced_name: parent.plant_resource_code
    :data_type: :string
    :width: 100
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  module:
    :name: module
    :sequence_no: 3
    :caption: Module
    :namespaced_name: sysres.system_resource_code
    :data_type: :string
    :width: 100
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  plant_resource_code:
    :name: plant_resource_code
    :sequence_no: 4
    :caption: Plant resource code
    :namespaced_name: p.plant_resource_code
    :data_type: :string
    :width: 120
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_setup_id:
    :name: product_setup_id
    :sequence_no: 5
    :caption: Product setup
    :namespaced_name: a.product_setup_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  product_setup_code:
    :name: product_setup_code
    :sequence_no: 6
    :caption: Product setup code
    :namespaced_name: 
    :data_type: :string
    :width: 350
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  packing_specification_item_code:
    :name: packing_specification_item_code
    :sequence_no: 7
    :caption: Packing specification item code
    :namespaced_name: 
    :data_type: :string
    :width: 350
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  work_order_item_code:
    :name: work_order_item_code
    :sequence_no: 8
    :caption: Work order item code
    :namespaced_name: 
    :data_type: :string
    :width: 200
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  system_code:
    :name: system_code
    :sequence_no: 9
    :caption: PKG BOM Code
    :namespaced_name: pm_boms.system_code
    :data_type: :string
    :width: 200
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  fg_marks:
    :name: fg_marks
    :sequence_no: 10
    :caption: FG Marks
    :namespaced_name: 
    :data_type: :string
    :width: 200
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  gtin_code:
    :name: gtin_code
    :sequence_no: 11
    :caption: GTIN Code
    :namespaced_name: s.gtin_code
    :data_type: :string
    :width: 200
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  label_template_id:
    :name: label_template_id
    :sequence_no: 12
    :caption: Label template
    :namespaced_name: a.label_template_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  label_template_name:
    :name: label_template_name
    :sequence_no: 13
    :caption: Label template name
    :namespaced_name: l.label_template_name
    :data_type: :string
    :width: 120
    :format: 
    :hide: false
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  packing_method_id:
    :name: packing_method_id
    :sequence_no: 14
    :caption: Packing method
    :namespaced_name: a.packing_method_id
    :data_type: :string
    :width: 120
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  packing_method_code:
    :name: packing_method_code
    :sequence_no: 15
    :caption: Packing method code
    :namespaced_name: pm.packing_method_code
    :data_type: :string
    :width: 120
    :format: 
    :hide: false
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  active:
    :name: active
    :sequence_no: 16
    :caption: Active
    :namespaced_name: a.active
    :data_type: :boolean
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: true
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  production_run_id:
    :name: production_run_id
    :sequence_no: 17
    :caption: Production run
    :namespaced_name: a.production_run_id
    :data_type: :integer
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  rebin:
    :name: rebin
    :sequence_no: 18
    :caption: Rebin
    :namespaced_name: s.rebin
    :data_type: :boolean
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
  colour_rule:
    :name: colour_rule
    :sequence_no: 19
    :caption: Colour rule
    :namespaced_name: 
    :data_type: :string
    :width: 
    :format: 
    :hide: true
    :pinned: 
    :groupable: false
    :group_by_seq: 
    :group_sum: false
    :group_avg: false
    :group_min: false
    :group_max: false
:query_parameter_definitions:
- :column: r.id
  :caption: Production Run id
  :data_type: :integer
  :control_type: :text
  :default_value: 
  :ordered_list: false
  :ui_priority: 1
  :list_def: 
