# frozen_string_literal: true

module MesscadaApp
  class PalletSequenceContract < Dry::Validation::Contract
    params do # rubocop:disable Metrics/BlockLength
      optional(:id).filled(:integer)
      optional(:pallet_id).filled(:integer)
      optional(:pallet_number).filled(Types::StrippedString)
      optional(:pallet_sequence_number).filled(:integer)
      required(:production_run_id).filled(:integer)
      optional(:farm_id).filled(:integer)
      required(:puc_id).filled(:integer)
      required(:orchard_id).filled(:integer)
      required(:cultivar_group_id).filled(:integer)
      optional(:cultivar_id).maybe(:integer)
      required(:product_resource_allocation_id).maybe(:integer)
      optional(:packhouse_resource_id).maybe(:integer)
      optional(:production_line_id).maybe(:integer)
      required(:season_id).filled(:integer)
      required(:marketing_variety_id).filled(:integer)
      optional(:customer_variety_id).maybe(:integer)
      optional(:std_fruit_size_count_id).maybe(:integer)
      required(:basic_pack_code_id).filled(:integer)
      required(:standard_pack_code_id).filled(:integer)
      required(:fruit_actual_counts_for_pack_id).maybe(:integer)
      required(:fruit_size_reference_id).maybe(:integer)
      required(:marketing_org_party_role_id).filled(:integer)
      required(:packed_tm_group_id).filled(:integer)
      required(:mark_id).filled(:integer)
      required(:inventory_code_id).filled(:integer)
      required(:pallet_format_id).filled(:integer)
      required(:cartons_per_pallet_id).filled(:integer)
      required(:pm_bom_id).maybe(:integer)
      optional(:extended_columns).maybe(:hash)
      optional(:client_size_reference).maybe(Types::StrippedString)
      optional(:client_product_code).maybe(Types::StrippedString)
      optional(:treatment_ids).maybe(:array).maybe { each(:integer) }
      optional(:marketing_order_number).maybe(Types::StrippedString)
      optional(:pm_type_id).maybe(:integer)
      optional(:pm_subtype_id).maybe(:integer)
      required(:carton_quantity).filled(:integer)
      required(:scanned_from_carton_id).maybe(:integer)
      optional(:exit_ref).maybe(Types::StrippedString)
      optional(:scrapped_at).maybe(:time)
      optional(:verification_result).maybe(Types::StrippedString)
      optional(:pallet_verification_failure_reason_id).maybe(:integer)
      optional(:verified_at).maybe(:time)
      optional(:nett_weight).maybe(:decimal)
      optional(:verified).maybe(:bool)
      optional(:verification_passed).maybe(:bool)
      required(:pick_ref).maybe(Types::StrippedString)
      required(:grade_id).filled(:integer)
      optional(:scrapped_from_pallet_id).maybe(:integer)
      optional(:removed_from_pallet).maybe(:bool)
      optional(:removed_from_pallet_at).maybe(:time)
      optional(:removed_from_pallet_id).maybe(:integer)
      optional(:verified_by).maybe(Types::StrippedString)
      optional(:created_by).maybe(Types::StrippedString)
      optional(:target_market_id).maybe(:integer)
      optional(:pm_mark_id).maybe(:integer)
      optional(:gtin_code).maybe(Types::StrippedString)
      optional(:rmt_class_id).maybe(:integer)
      optional(:packing_specification_item_id).maybe(:integer)
      optional(:tu_labour_product_id).maybe(:integer)
      optional(:ru_labour_product_id).maybe(:integer)
      optional(:fruit_sticker_ids).maybe(:array).maybe { each(:integer) }
      optional(:tu_sticker_ids).maybe(:array).maybe { each(:integer) }
      optional(:target_customer_party_role_id).maybe(:integer)
      optional(:depot_pallet).maybe(:bool)
      optional(:legacy_data).maybe(:hash)
      optional(:marketing_puc_id).maybe(:integer)
      optional(:marketing_orchard_id).maybe(:integer)
      optional(:created_at).maybe(:time)
      optional(:product_chars).maybe(Types::StrippedString)
      optional(:colour_percentage_id).maybe(:integer)
    end

    rule(:fruit_size_reference_id, :fruit_actual_counts_for_pack_id) do
      base.failure 'must provide either fruit_size_reference or fruit_actual_count' unless values[:fruit_size_reference_id] || values[:fruit_actual_counts_for_pack_id]
    end
    rule(:packhouse_resource_id, :production_line_id) do # depot_pltseq_ph_line_check
      base.failure 'must be a depot_pallet or provide packhouse_resource_id and production_line_id' unless values[:depot_pallet] || (values[:packhouse_resource_id] && values[:production_line_id])
    end
  end

  BinToPalletSequenceSchema = Dry::Schema.Params do # rubocop:disable Metrics/BlockLength
    optional(:id).filled(:integer)
    optional(:pallet_id).filled(:integer)
    optional(:pallet_number).filled(Types::StrippedString)
    optional(:pallet_sequence_number).filled(:integer)
    optional(:production_run_id).maybe(:integer)
    optional(:farm_id).filled(:integer)
    required(:puc_id).filled(:integer)
    required(:orchard_id).filled(:integer)
    required(:cultivar_group_id).filled(:integer)
    optional(:cultivar_id).maybe(:integer)
    optional(:product_resource_allocation_id).maybe(:integer)
    required(:packhouse_resource_id).filled(:integer)
    required(:production_line_id).filled(:integer)
    required(:season_id).filled(:integer)
    required(:marketing_variety_id).filled(:integer)
    optional(:customer_variety_id).maybe(:integer)
    optional(:std_fruit_size_count_id).maybe(:integer)
    required(:basic_pack_code_id).filled(:integer)
    required(:standard_pack_code_id).filled(:integer)
    optional(:fruit_actual_counts_for_pack_id).maybe(:integer)
    required(:fruit_size_reference_id).maybe(:integer)
    required(:marketing_org_party_role_id).filled(:integer)
    required(:packed_tm_group_id).filled(:integer)
    required(:mark_id).filled(:integer)
    required(:inventory_code_id).filled(:integer)
    required(:pallet_format_id).filled(:integer)
    required(:cartons_per_pallet_id).filled(:integer)
    optional(:pm_bom_id).maybe(:integer)
    optional(:extended_columns).maybe(:hash)
    optional(:client_size_reference).maybe(Types::StrippedString)
    optional(:client_product_code).maybe(Types::StrippedString)
    optional(:treatment_ids).maybe(:array).maybe { each(:integer) }
    optional(:marketing_order_number).maybe(Types::StrippedString)
    optional(:pm_type_id).maybe(:integer)
    optional(:pm_subtype_id).maybe(:integer)
    required(:carton_quantity).filled(:integer)
    optional(:scanned_from_carton_id).maybe(:integer)
    optional(:exit_ref).maybe(Types::StrippedString)
    optional(:scrapped_at).maybe(:time)
    optional(:verification_result).maybe(Types::StrippedString)
    optional(:pallet_verification_failure_reason_id).maybe(:integer)
    optional(:verified_at).maybe(:time)
    optional(:nett_weight).maybe(:decimal)
    optional(:verified).maybe(:bool)
    optional(:verification_passed).maybe(:bool)
    optional(:pick_ref).maybe(Types::StrippedString)
    required(:grade_id).filled(:integer)
    optional(:scrapped_from_pallet_id).maybe(:integer)
    optional(:removed_from_pallet).maybe(:bool)
    optional(:removed_from_pallet_at).maybe(:time)
    optional(:removed_from_pallet_id).maybe(:integer)
    optional(:verified_by).maybe(Types::StrippedString)
    optional(:created_by).maybe(Types::StrippedString)
    optional(:target_market_id).maybe(:integer)
    optional(:pm_mark_id).maybe(:integer)
    optional(:gtin_code).maybe(Types::StrippedString)
    optional(:rmt_class_id).maybe(:integer)
    optional(:packing_specification_item_id).maybe(:integer)
    optional(:tu_labour_product_id).maybe(:integer)
    optional(:ru_labour_product_id).maybe(:integer)
    optional(:fruit_sticker_ids).maybe(:array).maybe { each(:integer) }
    optional(:tu_sticker_ids).maybe(:array).maybe { each(:integer) }
    optional(:target_customer_party_role_id).maybe(:integer)
    optional(:product_chars).maybe(Types::StrippedString)
    optional(:colour_percentage_id).maybe(:integer)
  end
end
